- name: Install required system packages
  yum:
    name: 
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: latest
    update_cache: yes

- name: Add Docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Ensure Docker is installed
  yum:
    name: docker-ce
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes